### PR TITLE
set npm proxy from http_proxy env

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik ptal

**Comment by jhadvig** [comment]
LGTM :+1: 
... just one tiny proposal/nit, wouldn't it be also good to print the set http/https proxy address ?

**Comment by bparees** [comment]
@jhadvig yeah maybe. i did debate that :)

**Comment by jhadvig** [comment]
I see that the outcome of the debate was against the printing :-]

**Comment by bparees** [comment]
@jhadvig added.

**Comment by jhadvig** [comment]
ta ta ta taaa... I'm lovin' it :hamburger:

**Pull request merged**
