### PR TITLE
Rename /opt/openshift to /opt/app-root

### PR DESCRIPTION
**Pull request by humaton**

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
ok to test

**Comment by mfojtik** [comment]
ok to test

**Comment by bparees** [comment]
I assume this will fail until the sti-base changes get merged?

**Comment by mfojtik** [comment]
@bparees yes, the problem is that if we merge this and we don't fix other images then the other images might get broken....

**Comment by jhadvig** [comment]
@bparees will probably have to pospone the testing until the sti-base changes are merged and new sti-base images are build

**Comment by jhadvig** [comment]
LGTM

**Pull request merged**
