### PR TITLE
Card devexp_426 - Removing save-artifacts

### PR DESCRIPTION
**Pull request by soltysh**
@jhadvig PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
@soltysh this needs rebase

**Comment by soltysh** [comment]
Yeah, I just noticed that and here you have it.

**Comment by mfojtik** [comment]
@jhadvig can you please test this change locally if you get time? we can't trust Jenkins atm ;-)

**Comment by soltysh** [comment]
Rebased to fix conflicts.

**Comment by mfojtik** [comment]
LGTM

**Comment by jhadvig** [comment]
@soltysh I've tested the change and everything works && test are passing.
LGTM

**Pull request merged**
