### PR TITLE
Fix the label schema

### PR DESCRIPTION
**Pull request by mfojtik**
The 'chown' change is pending image rebuild for https://github.com/openshift/sti-base/pull/52

### CODE REVIEW

**Comment by soltysh** [comment]
LGTM

**Comment by soltysh** [comment]
LGTM still

**Comment by mfojtik** [comment]
@soltysh thanks! @bparees any last comments till I start copying this to all other Dockerfile(s)?

**Comment by bparees** [comment]
lgtm.

**Pull request merged**
