### PR TITLE
[DO NOT MERGE]Test to see if nodejs-nodemon is there

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
[test] doubt it but we'll see

**Comment by bparees** [comment]
looks like it worked.. @Ian-Stewart-Binks can you update your PR to install nodejs-nodemon via yum, for the rhel7 image?

**Comment by sdodson** [comment]
@bparees nefarious silent failure strikes again

```
No package nodejs-nodemon available.
```

**Comment by bparees** [comment]
@sdodson doh, thanks for actually looking at it.  hopefully @Ian-Stewart-Binks 's PR actually includes tests that would have caught that, but still.

so you think we need to add the other repo i guess?

**Comment by sdodson** [comment]
Yeah, I just don't know exactly what it should be to pickup the latest 3.1
puddles. May have to wait for @tdawson to chime in

**Comment by Ian-Stewart-Binks** [comment]
@bparees Sorry for my late reply, just returned from vacation. Should I still update the PR to install nodejs-nodemon through yum?

**Comment by bparees** [comment]
@Ian-Stewart-Binks sit tight until @sdodson and i figure out the right steps to make it yum installable.

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
[test] again

**Comment by bparees** [comment]
```
Installed:
  nodejs-nodemon.noarch 0:1.8.1-2.el7aos      nodejs010.x86_64 0:2.1-3.el7     
```

looks like you got it this time.

@Ian-Stewart-Binks , afraid you'll have to do something like this for the rhel7 portion of your nodejs image changes.

**Comment by bparees** [comment]
actually we should probably add this repo to the base rhel7 image we build this stuff on top of instead.  i'll work on making that happen.

**Comment by bparees** [comment]
this is resolved now, "yum install -y nodejs-nodemon" works w/ no other config/args needed, now that the rhaos repo is in the rhel7 image.

**Pull request closed without merging**
